version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-shop-assistant
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
      - ollama
      - selenium
      - scraping-website
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=db
      - DATABASE_NAME=mysql
      - SCRAPING_URL=http://scraping-website:3000
      - OLLAMA_CHAT_URL=http://ollama:11434/api/chat
      - OLLAMA_LIST_URL=http://ollama:11434/api/tags
      - COHERE_API_KEY=${COHERE_API_KEY}
      - SELENIUM_CHROME_URL=http://selenium:4444/wd/hub
    tty: true
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  ollama:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    pull_policy: always
    networks:
      - app-network
    tty: true
    entrypoint: [ "/usr/bin/bash", "/app/entrypoint.sh" ] 

  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    networks:
      - app-network
    shm_size: 4gb

  scraping-website:
    image: ${SHOP_IMG}
    ports:
      - "4000:3000"
    networks:
      - app-network

  

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
